
CREATE TABLE db_example ( 
  INT_VALUE     INTEGER NOT NULL, 
  STRING_VALUE  VARCHAR(50), 
  DOUBLE_VALUE  FLOAT, 
  EXAMPLE_LONG  INTEGER, 
  EXAMPLE_DATE  DATE ) ; 

CREATE TABLE db_example_backup ( 
  INT_VALUE     INTEGER NOT NULL, 
  STRING_VALUE  VARCHAR(50), 
  DOUBLE_VALUE  FLOAT, 
  EXAMPLE_LONG  INTEGER, 
  EXAMPLE_DATE  DATE ) ; 

CREATE TABLE db_sample ( 
  SAMPLE_LONG  INTEGER, 
  SAMPLE_INT   INTEGER, 
  SAMPLE_STR   VARCHAR(50), 
  EXTRA_FLOAT  FLOAT ) ; 

CREATE TABLE db_longstr ( 
  INT_VALUE     INTEGER NOT NULL, 
  STRING_VALUE  LONGTEXT, 
  DOUBLE_VALUE  FLOAT, 
  EXAMPLE_LONG  INTEGER, 
  EXAMPLE_DATE  DATE ) ;

CREATE TABLE long_example ( 
STRING_VALUE LONGTEXT 
); 

CREATE TABLE blob_example(
BLOB_VALUE BLOB
);

CREATE TABLE test_set (
   value SET('c1','c2') NOT NULL DEFAULT 'c1'
);

CREATE TABLE test_nullable (
   int_value INT,
   double_value DOUBLE 
);
